-- Generated by scripts/import_cloudcost_tools.py — DO NOT HAND-EDIT.

-- Source spec: migrations/seeds/cloud_cost_spec.json

-- AI-safe: GET-only + path blocklist; auth=user_passthrough; retries=0.

BEGIN;

INSERT INTO chat_gw.tools
    (name, display_name, description, category, dispatcher, config,
     auth_mode, secret_env_name, auth_header, auth_prefix, input_schema, output_schema)
VALUES (
    'cloud_cost.health',
    'CloudCost Health',
    $$用途: 探测 CloudCost 后端连通性。
何时使用: 对话前做一次快速自检。
返回: {status:'ok'}。$$,
    'cloud_cost',
    'http_adapter',
    '{"base_url_env": "CLOUDCOST_API_BASE", "method": "GET", "path": "/api/health", "retries": 0, "timeout_sec": 45}'::jsonb,
    'user_passthrough',
    NULL,
    'Authorization',
    'Bearer ',
    '{"additionalProperties": false, "properties": {}, "type": "object"}'::jsonb,
    NULL
)
ON CONFLICT (name) DO UPDATE SET
    display_name = EXCLUDED.display_name,
    description = EXCLUDED.description,
    category = EXCLUDED.category,
    dispatcher = EXCLUDED.dispatcher,
    config = EXCLUDED.config,
    auth_mode = EXCLUDED.auth_mode,
    secret_env_name = EXCLUDED.secret_env_name,
    auth_header = EXCLUDED.auth_header,
    auth_prefix = EXCLUDED.auth_prefix,
    input_schema = EXCLUDED.input_schema,
    output_schema = EXCLUDED.output_schema;

INSERT INTO chat_gw.tools
    (name, display_name, description, category, dispatcher, config,
     auth_mode, secret_env_name, auth_header, auth_prefix, input_schema, output_schema)
VALUES (
    'cloud_cost.auth_me',
    'CloudCost 当前身份与可见范围',
    $$用途: 返回当前 bearer token 绑定的用户信息与 visible_cloud_account_ids。
何时使用: 回答问题前确认数据口径 (admin 全量 / null / [] / [ids]).
出参: id/username/email/display_name/roles/visible_cloud_account_ids。$$,
    'cloud_cost',
    'http_adapter',
    '{"base_url_env": "CLOUDCOST_API_BASE", "method": "GET", "path": "/api/auth/me", "retries": 0, "timeout_sec": 45}'::jsonb,
    'user_passthrough',
    NULL,
    'Authorization',
    'Bearer ',
    '{"additionalProperties": false, "properties": {}, "type": "object"}'::jsonb,
    NULL
)
ON CONFLICT (name) DO UPDATE SET
    display_name = EXCLUDED.display_name,
    description = EXCLUDED.description,
    category = EXCLUDED.category,
    dispatcher = EXCLUDED.dispatcher,
    config = EXCLUDED.config,
    auth_mode = EXCLUDED.auth_mode,
    secret_env_name = EXCLUDED.secret_env_name,
    auth_header = EXCLUDED.auth_header,
    auth_prefix = EXCLUDED.auth_prefix,
    input_schema = EXCLUDED.input_schema,
    output_schema = EXCLUDED.output_schema;

INSERT INTO chat_gw.tools
    (name, display_name, description, category, dispatcher, config,
     auth_mode, secret_env_name, auth_header, auth_prefix, input_schema, output_schema)
VALUES (
    'cloud_cost.sync_last',
    'CloudCost 最近同步时间',
    $$用途: 查询 CloudCost 最后一次成功同步的 ISO8601 时间 (无时区)。
何时使用: 先确认数据新鲜度再讨论费用。
出参: {last_sync: string|null}.$$,
    'cloud_cost',
    'http_adapter',
    '{"base_url_env": "CLOUDCOST_API_BASE", "method": "GET", "path": "/api/sync/last", "retries": 0, "timeout_sec": 45}'::jsonb,
    'user_passthrough',
    NULL,
    'Authorization',
    'Bearer ',
    '{"additionalProperties": false, "properties": {}, "type": "object"}'::jsonb,
    NULL
)
ON CONFLICT (name) DO UPDATE SET
    display_name = EXCLUDED.display_name,
    description = EXCLUDED.description,
    category = EXCLUDED.category,
    dispatcher = EXCLUDED.dispatcher,
    config = EXCLUDED.config,
    auth_mode = EXCLUDED.auth_mode,
    secret_env_name = EXCLUDED.secret_env_name,
    auth_header = EXCLUDED.auth_header,
    auth_prefix = EXCLUDED.auth_prefix,
    input_schema = EXCLUDED.input_schema,
    output_schema = EXCLUDED.output_schema;

INSERT INTO chat_gw.tools
    (name, display_name, description, category, dispatcher, config,
     auth_mode, secret_env_name, auth_header, auth_prefix, input_schema, output_schema)
VALUES (
    'cloud_cost.dashboard_bundle',
    'CloudCost 首页聚合 Bundle',
    $$用途: 单次拿首页级总览 (overview + trend + by_provider + by_service).
何时使用: '本月云成本多少' 类宽口径问题.
参数: month YYYY-MM 必填; granularity (daily/weekly/monthly, 默认 daily); service_limit 1-100 默认 10.$$,
    'cloud_cost',
    'http_adapter',
    '{"base_url_env": "CLOUDCOST_API_BASE", "method": "GET", "param_map": {"granularity": "query", "month": "query", "service_limit": "query"}, "path": "/api/dashboard/bundle", "retries": 0, "timeout_sec": 45}'::jsonb,
    'user_passthrough',
    NULL,
    'Authorization',
    'Bearer ',
    '{"additionalProperties": false, "properties": {"granularity": {"default": "daily", "enum": ["daily", "weekly", "monthly"], "type": "string"}, "month": {"pattern": "^\\d{4}-\\d{2}$", "type": "string"}, "service_limit": {"default": 10, "maximum": 100, "minimum": 1, "type": "integer"}}, "required": ["month"], "type": "object"}'::jsonb,
    NULL
)
ON CONFLICT (name) DO UPDATE SET
    display_name = EXCLUDED.display_name,
    description = EXCLUDED.description,
    category = EXCLUDED.category,
    dispatcher = EXCLUDED.dispatcher,
    config = EXCLUDED.config,
    auth_mode = EXCLUDED.auth_mode,
    secret_env_name = EXCLUDED.secret_env_name,
    auth_header = EXCLUDED.auth_header,
    auth_prefix = EXCLUDED.auth_prefix,
    input_schema = EXCLUDED.input_schema,
    output_schema = EXCLUDED.output_schema;

INSERT INTO chat_gw.tools
    (name, display_name, description, category, dispatcher, config,
     auth_mode, secret_env_name, auth_header, auth_prefix, input_schema, output_schema)
VALUES (
    'cloud_cost.dashboard_overview',
    'CloudCost 月度总览卡片',
    $$用途: 只拿 overview 卡片 (total_cost, prev_month_cost, mom_change_pct, active_projects).
参数: month YYYY-MM 必填.$$,
    'cloud_cost',
    'http_adapter',
    '{"base_url_env": "CLOUDCOST_API_BASE", "method": "GET", "param_map": {"month": "query"}, "path": "/api/dashboard/overview", "retries": 0, "timeout_sec": 45}'::jsonb,
    'user_passthrough',
    NULL,
    'Authorization',
    'Bearer ',
    '{"additionalProperties": false, "properties": {"month": {"pattern": "^\\d{4}-\\d{2}$", "type": "string"}}, "required": ["month"], "type": "object"}'::jsonb,
    NULL
)
ON CONFLICT (name) DO UPDATE SET
    display_name = EXCLUDED.display_name,
    description = EXCLUDED.description,
    category = EXCLUDED.category,
    dispatcher = EXCLUDED.dispatcher,
    config = EXCLUDED.config,
    auth_mode = EXCLUDED.auth_mode,
    secret_env_name = EXCLUDED.secret_env_name,
    auth_header = EXCLUDED.auth_header,
    auth_prefix = EXCLUDED.auth_prefix,
    input_schema = EXCLUDED.input_schema,
    output_schema = EXCLUDED.output_schema;

INSERT INTO chat_gw.tools
    (name, display_name, description, category, dispatcher, config,
     auth_mode, secret_env_name, auth_header, auth_prefix, input_schema, output_schema)
VALUES (
    'cloud_cost.dashboard_trend',
    'CloudCost 费用趋势',
    $$用途: 多月区间内的费用趋势 (按 daily/weekly/monthly 粒度).
参数: start / end 都是 YYYY-MM; granularity 默认 daily.$$,
    'cloud_cost',
    'http_adapter',
    '{"base_url_env": "CLOUDCOST_API_BASE", "method": "GET", "param_map": {"end": "query", "granularity": "query", "start": "query"}, "path": "/api/dashboard/trend", "retries": 0, "timeout_sec": 45}'::jsonb,
    'user_passthrough',
    NULL,
    'Authorization',
    'Bearer ',
    '{"additionalProperties": false, "properties": {"end": {"pattern": "^\\d{4}-\\d{2}$", "type": "string"}, "granularity": {"default": "daily", "enum": ["daily", "weekly", "monthly"], "type": "string"}, "start": {"pattern": "^\\d{4}-\\d{2}$", "type": "string"}}, "required": ["start", "end"], "type": "object"}'::jsonb,
    NULL
)
ON CONFLICT (name) DO UPDATE SET
    display_name = EXCLUDED.display_name,
    description = EXCLUDED.description,
    category = EXCLUDED.category,
    dispatcher = EXCLUDED.dispatcher,
    config = EXCLUDED.config,
    auth_mode = EXCLUDED.auth_mode,
    secret_env_name = EXCLUDED.secret_env_name,
    auth_header = EXCLUDED.auth_header,
    auth_prefix = EXCLUDED.auth_prefix,
    input_schema = EXCLUDED.input_schema,
    output_schema = EXCLUDED.output_schema;

INSERT INTO chat_gw.tools
    (name, display_name, description, category, dispatcher, config,
     auth_mode, secret_env_name, auth_header, auth_prefix, input_schema, output_schema)
VALUES (
    'cloud_cost.dashboard_by_provider',
    'CloudCost 按云厂商拆分',
    $$用途: 按 aws/gcp/azure/taiji 的月度费用与占比.
参数: month YYYY-MM.$$,
    'cloud_cost',
    'http_adapter',
    '{"base_url_env": "CLOUDCOST_API_BASE", "method": "GET", "param_map": {"month": "query"}, "path": "/api/dashboard/by-provider", "retries": 0, "timeout_sec": 45}'::jsonb,
    'user_passthrough',
    NULL,
    'Authorization',
    'Bearer ',
    '{"additionalProperties": false, "properties": {"month": {"pattern": "^\\d{4}-\\d{2}$", "type": "string"}}, "required": ["month"], "type": "object"}'::jsonb,
    NULL
)
ON CONFLICT (name) DO UPDATE SET
    display_name = EXCLUDED.display_name,
    description = EXCLUDED.description,
    category = EXCLUDED.category,
    dispatcher = EXCLUDED.dispatcher,
    config = EXCLUDED.config,
    auth_mode = EXCLUDED.auth_mode,
    secret_env_name = EXCLUDED.secret_env_name,
    auth_header = EXCLUDED.auth_header,
    auth_prefix = EXCLUDED.auth_prefix,
    input_schema = EXCLUDED.input_schema,
    output_schema = EXCLUDED.output_schema;

INSERT INTO chat_gw.tools
    (name, display_name, description, category, dispatcher, config,
     auth_mode, secret_env_name, auth_header, auth_prefix, input_schema, output_schema)
VALUES (
    'cloud_cost.dashboard_by_category',
    'CloudCost 按费用分类拆分',
    $$用途: 按 categories 返回原始成本 / markup_rate / 加价后金额.
参数: month YYYY-MM.$$,
    'cloud_cost',
    'http_adapter',
    '{"base_url_env": "CLOUDCOST_API_BASE", "method": "GET", "param_map": {"month": "query"}, "path": "/api/dashboard/by-category", "retries": 0, "timeout_sec": 45}'::jsonb,
    'user_passthrough',
    NULL,
    'Authorization',
    'Bearer ',
    '{"additionalProperties": false, "properties": {"month": {"pattern": "^\\d{4}-\\d{2}$", "type": "string"}}, "required": ["month"], "type": "object"}'::jsonb,
    NULL
)
ON CONFLICT (name) DO UPDATE SET
    display_name = EXCLUDED.display_name,
    description = EXCLUDED.description,
    category = EXCLUDED.category,
    dispatcher = EXCLUDED.dispatcher,
    config = EXCLUDED.config,
    auth_mode = EXCLUDED.auth_mode,
    secret_env_name = EXCLUDED.secret_env_name,
    auth_header = EXCLUDED.auth_header,
    auth_prefix = EXCLUDED.auth_prefix,
    input_schema = EXCLUDED.input_schema,
    output_schema = EXCLUDED.output_schema;

INSERT INTO chat_gw.tools
    (name, display_name, description, category, dispatcher, config,
     auth_mode, secret_env_name, auth_header, auth_prefix, input_schema, output_schema)
VALUES (
    'cloud_cost.dashboard_by_project',
    'CloudCost 按项目 Top N',
    $$用途: 月度 Top N 项目费用列表 (云厂商侧 external_project_id).
参数: month YYYY-MM; limit 1-100 默认 10.$$,
    'cloud_cost',
    'http_adapter',
    '{"base_url_env": "CLOUDCOST_API_BASE", "method": "GET", "param_map": {"limit": "query", "month": "query"}, "path": "/api/dashboard/by-project", "retries": 0, "timeout_sec": 45}'::jsonb,
    'user_passthrough',
    NULL,
    'Authorization',
    'Bearer ',
    '{"additionalProperties": false, "properties": {"limit": {"default": 10, "maximum": 100, "minimum": 1, "type": "integer"}, "month": {"pattern": "^\\d{4}-\\d{2}$", "type": "string"}}, "required": ["month"], "type": "object"}'::jsonb,
    NULL
)
ON CONFLICT (name) DO UPDATE SET
    display_name = EXCLUDED.display_name,
    description = EXCLUDED.description,
    category = EXCLUDED.category,
    dispatcher = EXCLUDED.dispatcher,
    config = EXCLUDED.config,
    auth_mode = EXCLUDED.auth_mode,
    secret_env_name = EXCLUDED.secret_env_name,
    auth_header = EXCLUDED.auth_header,
    auth_prefix = EXCLUDED.auth_prefix,
    input_schema = EXCLUDED.input_schema,
    output_schema = EXCLUDED.output_schema;

INSERT INTO chat_gw.tools
    (name, display_name, description, category, dispatcher, config,
     auth_mode, secret_env_name, auth_header, auth_prefix, input_schema, output_schema)
VALUES (
    'cloud_cost.dashboard_by_service',
    'CloudCost 按服务 Top N',
    $$用途: 月度 Top N 服务 (product) 费用与占比.
参数: month YYYY-MM; provider 可选 (aws/gcp/azure/taiji); limit 1-100.$$,
    'cloud_cost',
    'http_adapter',
    '{"base_url_env": "CLOUDCOST_API_BASE", "method": "GET", "param_map": {"limit": "query", "month": "query", "provider": "query"}, "path": "/api/dashboard/by-service", "retries": 0, "timeout_sec": 45}'::jsonb,
    'user_passthrough',
    NULL,
    'Authorization',
    'Bearer ',
    '{"additionalProperties": false, "properties": {"limit": {"default": 10, "maximum": 100, "minimum": 1, "type": "integer"}, "month": {"pattern": "^\\d{4}-\\d{2}$", "type": "string"}, "provider": {"enum": ["aws", "gcp", "azure", "taiji"], "type": "string"}}, "required": ["month"], "type": "object"}'::jsonb,
    NULL
)
ON CONFLICT (name) DO UPDATE SET
    display_name = EXCLUDED.display_name,
    description = EXCLUDED.description,
    category = EXCLUDED.category,
    dispatcher = EXCLUDED.dispatcher,
    config = EXCLUDED.config,
    auth_mode = EXCLUDED.auth_mode,
    secret_env_name = EXCLUDED.secret_env_name,
    auth_header = EXCLUDED.auth_header,
    auth_prefix = EXCLUDED.auth_prefix,
    input_schema = EXCLUDED.input_schema,
    output_schema = EXCLUDED.output_schema;

INSERT INTO chat_gw.tools
    (name, display_name, description, category, dispatcher, config,
     auth_mode, secret_env_name, auth_header, auth_prefix, input_schema, output_schema)
VALUES (
    'cloud_cost.dashboard_by_region',
    'CloudCost 按区域拆分',
    $$用途: 月度 region 维度的费用列表.
参数: month YYYY-MM.$$,
    'cloud_cost',
    'http_adapter',
    '{"base_url_env": "CLOUDCOST_API_BASE", "method": "GET", "param_map": {"month": "query"}, "path": "/api/dashboard/by-region", "retries": 0, "timeout_sec": 45}'::jsonb,
    'user_passthrough',
    NULL,
    'Authorization',
    'Bearer ',
    '{"additionalProperties": false, "properties": {"month": {"pattern": "^\\d{4}-\\d{2}$", "type": "string"}}, "required": ["month"], "type": "object"}'::jsonb,
    NULL
)
ON CONFLICT (name) DO UPDATE SET
    display_name = EXCLUDED.display_name,
    description = EXCLUDED.description,
    category = EXCLUDED.category,
    dispatcher = EXCLUDED.dispatcher,
    config = EXCLUDED.config,
    auth_mode = EXCLUDED.auth_mode,
    secret_env_name = EXCLUDED.secret_env_name,
    auth_header = EXCLUDED.auth_header,
    auth_prefix = EXCLUDED.auth_prefix,
    input_schema = EXCLUDED.input_schema,
    output_schema = EXCLUDED.output_schema;

INSERT INTO chat_gw.tools
    (name, display_name, description, category, dispatcher, config,
     auth_mode, secret_env_name, auth_header, auth_prefix, input_schema, output_schema)
VALUES (
    'cloud_cost.dashboard_top_growth',
    'CloudCost 增长排行',
    $$用途: 按项目列出 growth_pct 最高的 N 个 (本周期 vs 上周期).
参数: period 默认 '7d'; limit 1-50.$$,
    'cloud_cost',
    'http_adapter',
    '{"base_url_env": "CLOUDCOST_API_BASE", "method": "GET", "param_map": {"limit": "query", "period": "query"}, "path": "/api/dashboard/top-growth", "retries": 0, "timeout_sec": 45}'::jsonb,
    'user_passthrough',
    NULL,
    'Authorization',
    'Bearer ',
    '{"additionalProperties": false, "properties": {"limit": {"default": 10, "maximum": 50, "minimum": 1, "type": "integer"}, "period": {"default": "7d", "type": "string"}}, "type": "object"}'::jsonb,
    NULL
)
ON CONFLICT (name) DO UPDATE SET
    display_name = EXCLUDED.display_name,
    description = EXCLUDED.description,
    category = EXCLUDED.category,
    dispatcher = EXCLUDED.dispatcher,
    config = EXCLUDED.config,
    auth_mode = EXCLUDED.auth_mode,
    secret_env_name = EXCLUDED.secret_env_name,
    auth_header = EXCLUDED.auth_header,
    auth_prefix = EXCLUDED.auth_prefix,
    input_schema = EXCLUDED.input_schema,
    output_schema = EXCLUDED.output_schema;

INSERT INTO chat_gw.tools
    (name, display_name, description, category, dispatcher, config,
     auth_mode, secret_env_name, auth_header, auth_prefix, input_schema, output_schema)
VALUES (
    'cloud_cost.dashboard_unassigned',
    'CloudCost 未归属项目',
    $$用途: 列出账单里存在但未与本地 projects 关联的外部项目.
参数: month YYYY-MM.$$,
    'cloud_cost',
    'http_adapter',
    '{"base_url_env": "CLOUDCOST_API_BASE", "method": "GET", "param_map": {"month": "query"}, "path": "/api/dashboard/unassigned", "retries": 0, "timeout_sec": 45}'::jsonb,
    'user_passthrough',
    NULL,
    'Authorization',
    'Bearer ',
    '{"additionalProperties": false, "properties": {"month": {"pattern": "^\\d{4}-\\d{2}$", "type": "string"}}, "required": ["month"], "type": "object"}'::jsonb,
    NULL
)
ON CONFLICT (name) DO UPDATE SET
    display_name = EXCLUDED.display_name,
    description = EXCLUDED.description,
    category = EXCLUDED.category,
    dispatcher = EXCLUDED.dispatcher,
    config = EXCLUDED.config,
    auth_mode = EXCLUDED.auth_mode,
    secret_env_name = EXCLUDED.secret_env_name,
    auth_header = EXCLUDED.auth_header,
    auth_prefix = EXCLUDED.auth_prefix,
    input_schema = EXCLUDED.input_schema,
    output_schema = EXCLUDED.output_schema;

INSERT INTO chat_gw.tools
    (name, display_name, description, category, dispatcher, config,
     auth_mode, secret_env_name, auth_header, auth_prefix, input_schema, output_schema)
VALUES (
    'cloud_cost.metering_summary',
    'CloudCost Metering 汇总',
    $$用途: 日期区间/provider/服务/账号作用域内的 total_cost / total_usage / record_count / service_count.
金额 & 用量为 string (Decimal), 调用方自行 float()。
多选参数: account_ids / products 使用重复 query 语法.$$,
    'cloud_cost',
    'http_adapter',
    '{"base_url_env": "CLOUDCOST_API_BASE", "method": "GET", "param_map": {"account_id": "query", "account_ids": "query", "data_source_id": "query", "date_end": "query", "date_start": "query", "product": "query", "products": "query", "provider": "query", "supplier_name": "query", "supply_source_id": "query"}, "path": "/api/metering/summary", "retries": 0, "timeout_sec": 45}'::jsonb,
    'user_passthrough',
    NULL,
    'Authorization',
    'Bearer ',
    '{"additionalProperties": false, "properties": {"account_id": {"type": "integer"}, "account_ids": {"description": "重复 query 语法; 非空时覆盖 account_id", "items": {"type": "integer"}, "type": "array"}, "data_source_id": {"type": "integer"}, "date_end": {"format": "date", "type": "string"}, "date_start": {"format": "date", "type": "string"}, "product": {"type": "string"}, "products": {"description": "重复 query 语法; 非空时覆盖 product", "items": {"type": "string"}, "type": "array"}, "provider": {"enum": ["aws", "gcp", "azure", "taiji"], "type": "string"}, "supplier_name": {"type": "string"}, "supply_source_id": {"type": "integer"}}, "type": "object"}'::jsonb,
    NULL
)
ON CONFLICT (name) DO UPDATE SET
    display_name = EXCLUDED.display_name,
    description = EXCLUDED.description,
    category = EXCLUDED.category,
    dispatcher = EXCLUDED.dispatcher,
    config = EXCLUDED.config,
    auth_mode = EXCLUDED.auth_mode,
    secret_env_name = EXCLUDED.secret_env_name,
    auth_header = EXCLUDED.auth_header,
    auth_prefix = EXCLUDED.auth_prefix,
    input_schema = EXCLUDED.input_schema,
    output_schema = EXCLUDED.output_schema;

INSERT INTO chat_gw.tools
    (name, display_name, description, category, dispatcher, config,
     auth_mode, secret_env_name, auth_header, auth_prefix, input_schema, output_schema)
VALUES (
    'cloud_cost.metering_daily',
    'CloudCost Metering 按日',
    $$用途: 按日聚合 cost / usage_quantity / record_count (均为 string Decimal, 除 record_count 整型).
作用域/筛选同 summary.$$,
    'cloud_cost',
    'http_adapter',
    '{"base_url_env": "CLOUDCOST_API_BASE", "method": "GET", "param_map": {"account_id": "query", "account_ids": "query", "data_source_id": "query", "date_end": "query", "date_start": "query", "product": "query", "products": "query", "provider": "query", "supplier_name": "query", "supply_source_id": "query"}, "path": "/api/metering/daily", "retries": 0, "timeout_sec": 45}'::jsonb,
    'user_passthrough',
    NULL,
    'Authorization',
    'Bearer ',
    '{"additionalProperties": false, "properties": {"account_id": {"type": "integer"}, "account_ids": {"items": {"type": "integer"}, "type": "array"}, "data_source_id": {"type": "integer"}, "date_end": {"format": "date", "type": "string"}, "date_start": {"format": "date", "type": "string"}, "product": {"type": "string"}, "products": {"items": {"type": "string"}, "type": "array"}, "provider": {"enum": ["aws", "gcp", "azure", "taiji"], "type": "string"}, "supplier_name": {"type": "string"}, "supply_source_id": {"type": "integer"}}, "type": "object"}'::jsonb,
    NULL
)
ON CONFLICT (name) DO UPDATE SET
    display_name = EXCLUDED.display_name,
    description = EXCLUDED.description,
    category = EXCLUDED.category,
    dispatcher = EXCLUDED.dispatcher,
    config = EXCLUDED.config,
    auth_mode = EXCLUDED.auth_mode,
    secret_env_name = EXCLUDED.secret_env_name,
    auth_header = EXCLUDED.auth_header,
    auth_prefix = EXCLUDED.auth_prefix,
    input_schema = EXCLUDED.input_schema,
    output_schema = EXCLUDED.output_schema;

INSERT INTO chat_gw.tools
    (name, display_name, description, category, dispatcher, config,
     auth_mode, secret_env_name, auth_header, auth_prefix, input_schema, output_schema)
VALUES (
    'cloud_cost.metering_by_service',
    'CloudCost Metering 按服务',
    $$用途: 按 product 聚合费用与用量 (Top N 分析场景).
筛选同 summary (无 product 过滤自身).
注意: 不同 usage_unit 的同名 product 会单独出现, unit 可能为 null.$$,
    'cloud_cost',
    'http_adapter',
    '{"base_url_env": "CLOUDCOST_API_BASE", "method": "GET", "param_map": {"account_id": "query", "account_ids": "query", "data_source_id": "query", "date_end": "query", "date_start": "query", "products": "query", "provider": "query", "supplier_name": "query", "supply_source_id": "query"}, "path": "/api/metering/by-service", "retries": 0, "timeout_sec": 45}'::jsonb,
    'user_passthrough',
    NULL,
    'Authorization',
    'Bearer ',
    '{"additionalProperties": false, "properties": {"account_id": {"type": "integer"}, "account_ids": {"items": {"type": "integer"}, "type": "array"}, "data_source_id": {"type": "integer"}, "date_end": {"format": "date", "type": "string"}, "date_start": {"format": "date", "type": "string"}, "products": {"items": {"type": "string"}, "type": "array"}, "provider": {"enum": ["aws", "gcp", "azure", "taiji"], "type": "string"}, "supplier_name": {"type": "string"}, "supply_source_id": {"type": "integer"}}, "type": "object"}'::jsonb,
    NULL
)
ON CONFLICT (name) DO UPDATE SET
    display_name = EXCLUDED.display_name,
    description = EXCLUDED.description,
    category = EXCLUDED.category,
    dispatcher = EXCLUDED.dispatcher,
    config = EXCLUDED.config,
    auth_mode = EXCLUDED.auth_mode,
    secret_env_name = EXCLUDED.secret_env_name,
    auth_header = EXCLUDED.auth_header,
    auth_prefix = EXCLUDED.auth_prefix,
    input_schema = EXCLUDED.input_schema,
    output_schema = EXCLUDED.output_schema;

INSERT INTO chat_gw.tools
    (name, display_name, description, category, dispatcher, config,
     auth_mode, secret_env_name, auth_header, auth_prefix, input_schema, output_schema)
VALUES (
    'cloud_cost.metering_detail',
    'CloudCost Metering 明细',
    $$用途: 原始明细分页. page 默认 1; page_size 默认 50, 上限 500.
金额/用量为 string (Decimal).$$,
    'cloud_cost',
    'http_adapter',
    '{"base_url_env": "CLOUDCOST_API_BASE", "method": "GET", "param_map": {"account_id": "query", "account_ids": "query", "data_source_id": "query", "date_end": "query", "date_start": "query", "page": "query", "page_size": "query", "product": "query", "products": "query", "provider": "query", "supplier_name": "query", "supply_source_id": "query"}, "path": "/api/metering/detail", "retries": 0, "timeout_sec": 45}'::jsonb,
    'user_passthrough',
    NULL,
    'Authorization',
    'Bearer ',
    '{"additionalProperties": false, "properties": {"account_id": {"type": "integer"}, "account_ids": {"items": {"type": "integer"}, "type": "array"}, "data_source_id": {"type": "integer"}, "date_end": {"format": "date", "type": "string"}, "date_start": {"format": "date", "type": "string"}, "page": {"default": 1, "minimum": 1, "type": "integer"}, "page_size": {"default": 50, "maximum": 500, "minimum": 1, "type": "integer"}, "product": {"type": "string"}, "products": {"items": {"type": "string"}, "type": "array"}, "provider": {"enum": ["aws", "gcp", "azure", "taiji"], "type": "string"}, "supplier_name": {"type": "string"}, "supply_source_id": {"type": "integer"}}, "type": "object"}'::jsonb,
    NULL
)
ON CONFLICT (name) DO UPDATE SET
    display_name = EXCLUDED.display_name,
    description = EXCLUDED.description,
    category = EXCLUDED.category,
    dispatcher = EXCLUDED.dispatcher,
    config = EXCLUDED.config,
    auth_mode = EXCLUDED.auth_mode,
    secret_env_name = EXCLUDED.secret_env_name,
    auth_header = EXCLUDED.auth_header,
    auth_prefix = EXCLUDED.auth_prefix,
    input_schema = EXCLUDED.input_schema,
    output_schema = EXCLUDED.output_schema;

INSERT INTO chat_gw.tools
    (name, display_name, description, category, dispatcher, config,
     auth_mode, secret_env_name, auth_header, auth_prefix, input_schema, output_schema)
VALUES (
    'cloud_cost.metering_detail_count',
    'CloudCost Metering 明细条数',
    $$用途: 在相同筛选下返回 {total}. 用于分页计算.$$,
    'cloud_cost',
    'http_adapter',
    '{"base_url_env": "CLOUDCOST_API_BASE", "method": "GET", "param_map": {"account_id": "query", "account_ids": "query", "data_source_id": "query", "date_end": "query", "date_start": "query", "product": "query", "products": "query", "provider": "query", "supplier_name": "query", "supply_source_id": "query"}, "path": "/api/metering/detail/count", "retries": 0, "timeout_sec": 45}'::jsonb,
    'user_passthrough',
    NULL,
    'Authorization',
    'Bearer ',
    '{"additionalProperties": false, "properties": {"account_id": {"type": "integer"}, "account_ids": {"items": {"type": "integer"}, "type": "array"}, "data_source_id": {"type": "integer"}, "date_end": {"format": "date", "type": "string"}, "date_start": {"format": "date", "type": "string"}, "product": {"type": "string"}, "products": {"items": {"type": "string"}, "type": "array"}, "provider": {"enum": ["aws", "gcp", "azure", "taiji"], "type": "string"}, "supplier_name": {"type": "string"}, "supply_source_id": {"type": "integer"}}, "type": "object"}'::jsonb,
    NULL
)
ON CONFLICT (name) DO UPDATE SET
    display_name = EXCLUDED.display_name,
    description = EXCLUDED.description,
    category = EXCLUDED.category,
    dispatcher = EXCLUDED.dispatcher,
    config = EXCLUDED.config,
    auth_mode = EXCLUDED.auth_mode,
    secret_env_name = EXCLUDED.secret_env_name,
    auth_header = EXCLUDED.auth_header,
    auth_prefix = EXCLUDED.auth_prefix,
    input_schema = EXCLUDED.input_schema,
    output_schema = EXCLUDED.output_schema;

INSERT INTO chat_gw.tools
    (name, display_name, description, category, dispatcher, config,
     auth_mode, secret_env_name, auth_header, auth_prefix, input_schema, output_schema)
VALUES (
    'cloud_cost.metering_products',
    'CloudCost Metering 产品列表',
    $$用途: 产品去重下拉, 用于 UI 或 agent 反查可用 product 名称.
参数: provider / account_id / supply_source_id / supplier_name / data_source_id.$$,
    'cloud_cost',
    'http_adapter',
    '{"base_url_env": "CLOUDCOST_API_BASE", "method": "GET", "param_map": {"account_id": "query", "data_source_id": "query", "provider": "query", "supplier_name": "query", "supply_source_id": "query"}, "path": "/api/metering/products", "retries": 0, "timeout_sec": 45}'::jsonb,
    'user_passthrough',
    NULL,
    'Authorization',
    'Bearer ',
    '{"additionalProperties": false, "properties": {"account_id": {"type": "integer"}, "data_source_id": {"type": "integer"}, "provider": {"enum": ["aws", "gcp", "azure", "taiji"], "type": "string"}, "supplier_name": {"type": "string"}, "supply_source_id": {"type": "integer"}}, "type": "object"}'::jsonb,
    NULL
)
ON CONFLICT (name) DO UPDATE SET
    display_name = EXCLUDED.display_name,
    description = EXCLUDED.description,
    category = EXCLUDED.category,
    dispatcher = EXCLUDED.dispatcher,
    config = EXCLUDED.config,
    auth_mode = EXCLUDED.auth_mode,
    secret_env_name = EXCLUDED.secret_env_name,
    auth_header = EXCLUDED.auth_header,
    auth_prefix = EXCLUDED.auth_prefix,
    input_schema = EXCLUDED.input_schema,
    output_schema = EXCLUDED.output_schema;

INSERT INTO chat_gw.tools
    (name, display_name, description, category, dispatcher, config,
     auth_mode, secret_env_name, auth_header, auth_prefix, input_schema, output_schema)
VALUES (
    'cloud_cost.billing_detail',
    'CloudCost Billing 明细',
    $$用途: 计费明细分页 (区别于 metering: billing 带 project_name).
page_size 默认 50, 上限 500. 金额/用量为 string (Decimal).$$,
    'cloud_cost',
    'http_adapter',
    '{"base_url_env": "CLOUDCOST_API_BASE", "method": "GET", "param_map": {"date_end": "query", "date_start": "query", "page": "query", "page_size": "query", "product": "query", "project_id": "query", "provider": "query"}, "path": "/api/billing/detail", "retries": 0, "timeout_sec": 45}'::jsonb,
    'user_passthrough',
    NULL,
    'Authorization',
    'Bearer ',
    '{"additionalProperties": false, "properties": {"date_end": {"format": "date", "type": "string"}, "date_start": {"format": "date", "type": "string"}, "page": {"default": 1, "minimum": 1, "type": "integer"}, "page_size": {"default": 50, "maximum": 500, "minimum": 1, "type": "integer"}, "product": {"type": "string"}, "project_id": {"description": "云厂商侧 project_id (非本地 projects.id)", "type": "string"}, "provider": {"enum": ["aws", "gcp", "azure", "taiji"], "type": "string"}}, "type": "object"}'::jsonb,
    NULL
)
ON CONFLICT (name) DO UPDATE SET
    display_name = EXCLUDED.display_name,
    description = EXCLUDED.description,
    category = EXCLUDED.category,
    dispatcher = EXCLUDED.dispatcher,
    config = EXCLUDED.config,
    auth_mode = EXCLUDED.auth_mode,
    secret_env_name = EXCLUDED.secret_env_name,
    auth_header = EXCLUDED.auth_header,
    auth_prefix = EXCLUDED.auth_prefix,
    input_schema = EXCLUDED.input_schema,
    output_schema = EXCLUDED.output_schema;

INSERT INTO chat_gw.tools
    (name, display_name, description, category, dispatcher, config,
     auth_mode, secret_env_name, auth_header, auth_prefix, input_schema, output_schema)
VALUES (
    'cloud_cost.billing_detail_count',
    'CloudCost Billing 明细条数',
    $$用途: 在同 billing/detail 筛选下的 {total}.$$,
    'cloud_cost',
    'http_adapter',
    '{"base_url_env": "CLOUDCOST_API_BASE", "method": "GET", "param_map": {"date_end": "query", "date_start": "query", "product": "query", "project_id": "query", "provider": "query"}, "path": "/api/billing/detail/count", "retries": 0, "timeout_sec": 45}'::jsonb,
    'user_passthrough',
    NULL,
    'Authorization',
    'Bearer ',
    '{"additionalProperties": false, "properties": {"date_end": {"format": "date", "type": "string"}, "date_start": {"format": "date", "type": "string"}, "product": {"type": "string"}, "project_id": {"type": "string"}, "provider": {"enum": ["aws", "gcp", "azure", "taiji"], "type": "string"}}, "type": "object"}'::jsonb,
    NULL
)
ON CONFLICT (name) DO UPDATE SET
    display_name = EXCLUDED.display_name,
    description = EXCLUDED.description,
    category = EXCLUDED.category,
    dispatcher = EXCLUDED.dispatcher,
    config = EXCLUDED.config,
    auth_mode = EXCLUDED.auth_mode,
    secret_env_name = EXCLUDED.secret_env_name,
    auth_header = EXCLUDED.auth_header,
    auth_prefix = EXCLUDED.auth_prefix,
    input_schema = EXCLUDED.input_schema,
    output_schema = EXCLUDED.output_schema;

INSERT INTO chat_gw.tools
    (name, display_name, description, category, dispatcher, config,
     auth_mode, secret_env_name, auth_header, auth_prefix, input_schema, output_schema)
VALUES (
    'cloud_cost.service_accounts_list',
    'CloudCost 服务账号列表',
    $$用途: 列出本地 service accounts. 任意登录角色可读.
入参: provider / status / customer_code / page / page_size.
注: secret_fields 仅列出字段名, 不含值.$$,
    'cloud_cost',
    'http_adapter',
    '{"base_url_env": "CLOUDCOST_API_BASE", "method": "GET", "param_map": {"customer_code": "query", "page": "query", "page_size": "query", "provider": "query", "status": "query"}, "path": "/api/service-accounts/", "retries": 0, "timeout_sec": 45}'::jsonb,
    'user_passthrough',
    NULL,
    'Authorization',
    'Bearer ',
    '{"additionalProperties": false, "properties": {"customer_code": {"type": "string"}, "page": {"default": 1, "minimum": 1, "type": "integer"}, "page_size": {"default": 100, "maximum": 500, "minimum": 1, "type": "integer"}, "provider": {"enum": ["aws", "gcp", "azure", "taiji"], "type": "string"}, "status": {"enum": ["active", "standby", "inactive"], "type": "string"}}, "type": "object"}'::jsonb,
    NULL
)
ON CONFLICT (name) DO UPDATE SET
    display_name = EXCLUDED.display_name,
    description = EXCLUDED.description,
    category = EXCLUDED.category,
    dispatcher = EXCLUDED.dispatcher,
    config = EXCLUDED.config,
    auth_mode = EXCLUDED.auth_mode,
    secret_env_name = EXCLUDED.secret_env_name,
    auth_header = EXCLUDED.auth_header,
    auth_prefix = EXCLUDED.auth_prefix,
    input_schema = EXCLUDED.input_schema,
    output_schema = EXCLUDED.output_schema;

INSERT INTO chat_gw.tools
    (name, display_name, description, category, dispatcher, config,
     auth_mode, secret_env_name, auth_header, auth_prefix, input_schema, output_schema)
VALUES (
    'cloud_cost.service_account_get',
    'CloudCost 服务账号详情',
    $$用途: 单个服务账号 (含 history / secret_fields 字段名).
路径参数: account_id 必填.$$,
    'cloud_cost',
    'http_adapter',
    '{"base_url_env": "CLOUDCOST_API_BASE", "method": "GET", "param_map": {"account_id": "path"}, "path": "/api/service-accounts/{account_id}", "retries": 0, "timeout_sec": 45}'::jsonb,
    'user_passthrough',
    NULL,
    'Authorization',
    'Bearer ',
    '{"additionalProperties": false, "properties": {"account_id": {"minimum": 1, "type": "integer"}}, "required": ["account_id"], "type": "object"}'::jsonb,
    NULL
)
ON CONFLICT (name) DO UPDATE SET
    display_name = EXCLUDED.display_name,
    description = EXCLUDED.description,
    category = EXCLUDED.category,
    dispatcher = EXCLUDED.dispatcher,
    config = EXCLUDED.config,
    auth_mode = EXCLUDED.auth_mode,
    secret_env_name = EXCLUDED.secret_env_name,
    auth_header = EXCLUDED.auth_header,
    auth_prefix = EXCLUDED.auth_prefix,
    input_schema = EXCLUDED.input_schema,
    output_schema = EXCLUDED.output_schema;

INSERT INTO chat_gw.tools
    (name, display_name, description, category, dispatcher, config,
     auth_mode, secret_env_name, auth_header, auth_prefix, input_schema, output_schema)
VALUES (
    'cloud_cost.service_account_costs',
    'CloudCost 服务账号费用汇总',
    $$用途: 指定账号 start_date..end_date 的 total_cost / services[] / daily[] / daily_by_service[]. 金额为 JSON number.
路径: account_id; 参数: start_date / end_date 必填 YYYY-MM-DD.$$,
    'cloud_cost',
    'http_adapter',
    '{"base_url_env": "CLOUDCOST_API_BASE", "method": "GET", "param_map": {"account_id": "path", "end_date": "query", "start_date": "query"}, "path": "/api/service-accounts/{account_id}/costs", "retries": 0, "timeout_sec": 45}'::jsonb,
    'user_passthrough',
    NULL,
    'Authorization',
    'Bearer ',
    '{"additionalProperties": false, "properties": {"account_id": {"minimum": 1, "type": "integer"}, "end_date": {"format": "date", "type": "string"}, "start_date": {"format": "date", "type": "string"}}, "required": ["account_id", "start_date", "end_date"], "type": "object"}'::jsonb,
    NULL
)
ON CONFLICT (name) DO UPDATE SET
    display_name = EXCLUDED.display_name,
    description = EXCLUDED.description,
    category = EXCLUDED.category,
    dispatcher = EXCLUDED.dispatcher,
    config = EXCLUDED.config,
    auth_mode = EXCLUDED.auth_mode,
    secret_env_name = EXCLUDED.secret_env_name,
    auth_header = EXCLUDED.auth_header,
    auth_prefix = EXCLUDED.auth_prefix,
    input_schema = EXCLUDED.input_schema,
    output_schema = EXCLUDED.output_schema;

INSERT INTO chat_gw.tools
    (name, display_name, description, category, dispatcher, config,
     auth_mode, secret_env_name, auth_header, auth_prefix, input_schema, output_schema)
VALUES (
    'cloud_cost.service_accounts_daily_report',
    'CloudCost 服务账号日报',
    $$用途: 统计页日报数据: 每行 (account_id, date, product) 聚合后的 cost (JSON number).
参数: start_date / end_date 必填; provider 可选.$$,
    'cloud_cost',
    'http_adapter',
    '{"base_url_env": "CLOUDCOST_API_BASE", "method": "GET", "param_map": {"end_date": "query", "provider": "query", "start_date": "query"}, "path": "/api/service-accounts/daily-report", "retries": 0, "timeout_sec": 45}'::jsonb,
    'user_passthrough',
    NULL,
    'Authorization',
    'Bearer ',
    '{"additionalProperties": false, "properties": {"end_date": {"format": "date", "type": "string"}, "provider": {"enum": ["aws", "gcp", "azure", "taiji"], "type": "string"}, "start_date": {"format": "date", "type": "string"}}, "required": ["start_date", "end_date"], "type": "object"}'::jsonb,
    NULL
)
ON CONFLICT (name) DO UPDATE SET
    display_name = EXCLUDED.display_name,
    description = EXCLUDED.description,
    category = EXCLUDED.category,
    dispatcher = EXCLUDED.dispatcher,
    config = EXCLUDED.config,
    auth_mode = EXCLUDED.auth_mode,
    secret_env_name = EXCLUDED.secret_env_name,
    auth_header = EXCLUDED.auth_header,
    auth_prefix = EXCLUDED.auth_prefix,
    input_schema = EXCLUDED.input_schema,
    output_schema = EXCLUDED.output_schema;

INSERT INTO chat_gw.tools
    (name, display_name, description, category, dispatcher, config,
     auth_mode, secret_env_name, auth_header, auth_prefix, input_schema, output_schema)
VALUES (
    'cloud_cost.projects_list',
    'CloudCost Projects 列表',
    $$用途: 老 Project CRUD 的只读视图 (本地 projects 表). 前端不用, 仅历史集成.
参数: status / provider / page / page_size.$$,
    'cloud_cost',
    'http_adapter',
    '{"base_url_env": "CLOUDCOST_API_BASE", "method": "GET", "param_map": {"page": "query", "page_size": "query", "provider": "query", "status": "query"}, "path": "/api/projects/", "retries": 0, "timeout_sec": 45}'::jsonb,
    'user_passthrough',
    NULL,
    'Authorization',
    'Bearer ',
    '{"additionalProperties": false, "properties": {"page": {"default": 1, "minimum": 1, "type": "integer"}, "page_size": {"default": 100, "maximum": 500, "minimum": 1, "type": "integer"}, "provider": {"enum": ["aws", "gcp", "azure", "taiji"], "type": "string"}, "status": {"enum": ["active", "standby", "inactive"], "type": "string"}}, "type": "object"}'::jsonb,
    NULL
)
ON CONFLICT (name) DO UPDATE SET
    display_name = EXCLUDED.display_name,
    description = EXCLUDED.description,
    category = EXCLUDED.category,
    dispatcher = EXCLUDED.dispatcher,
    config = EXCLUDED.config,
    auth_mode = EXCLUDED.auth_mode,
    secret_env_name = EXCLUDED.secret_env_name,
    auth_header = EXCLUDED.auth_header,
    auth_prefix = EXCLUDED.auth_prefix,
    input_schema = EXCLUDED.input_schema,
    output_schema = EXCLUDED.output_schema;

INSERT INTO chat_gw.tools
    (name, display_name, description, category, dispatcher, config,
     auth_mode, secret_env_name, auth_header, auth_prefix, input_schema, output_schema)
VALUES (
    'cloud_cost.project_get',
    'CloudCost Project 详情',
    $$用途: 单个 project (本地 projects.id).
路径: project_id 必填.$$,
    'cloud_cost',
    'http_adapter',
    '{"base_url_env": "CLOUDCOST_API_BASE", "method": "GET", "param_map": {"project_id": "path"}, "path": "/api/projects/{project_id}", "retries": 0, "timeout_sec": 45}'::jsonb,
    'user_passthrough',
    NULL,
    'Authorization',
    'Bearer ',
    '{"additionalProperties": false, "properties": {"project_id": {"minimum": 1, "type": "integer"}}, "required": ["project_id"], "type": "object"}'::jsonb,
    NULL
)
ON CONFLICT (name) DO UPDATE SET
    display_name = EXCLUDED.display_name,
    description = EXCLUDED.description,
    category = EXCLUDED.category,
    dispatcher = EXCLUDED.dispatcher,
    config = EXCLUDED.config,
    auth_mode = EXCLUDED.auth_mode,
    secret_env_name = EXCLUDED.secret_env_name,
    auth_header = EXCLUDED.auth_header,
    auth_prefix = EXCLUDED.auth_prefix,
    input_schema = EXCLUDED.input_schema,
    output_schema = EXCLUDED.output_schema;

INSERT INTO chat_gw.tools
    (name, display_name, description, category, dispatcher, config,
     auth_mode, secret_env_name, auth_header, auth_prefix, input_schema, output_schema)
VALUES (
    'cloud_cost.project_assignment_logs',
    'CloudCost Project 分配日志',
    $$用途: 项目的 customer/状态变更日志 (只读).
路径: project_id 必填.$$,
    'cloud_cost',
    'http_adapter',
    '{"base_url_env": "CLOUDCOST_API_BASE", "method": "GET", "param_map": {"project_id": "path"}, "path": "/api/projects/{project_id}/assignment-logs", "retries": 0, "timeout_sec": 45}'::jsonb,
    'user_passthrough',
    NULL,
    'Authorization',
    'Bearer ',
    '{"additionalProperties": false, "properties": {"project_id": {"minimum": 1, "type": "integer"}}, "required": ["project_id"], "type": "object"}'::jsonb,
    NULL
)
ON CONFLICT (name) DO UPDATE SET
    display_name = EXCLUDED.display_name,
    description = EXCLUDED.description,
    category = EXCLUDED.category,
    dispatcher = EXCLUDED.dispatcher,
    config = EXCLUDED.config,
    auth_mode = EXCLUDED.auth_mode,
    secret_env_name = EXCLUDED.secret_env_name,
    auth_header = EXCLUDED.auth_header,
    auth_prefix = EXCLUDED.auth_prefix,
    input_schema = EXCLUDED.input_schema,
    output_schema = EXCLUDED.output_schema;

INSERT INTO chat_gw.tools
    (name, display_name, description, category, dispatcher, config,
     auth_mode, secret_env_name, auth_header, auth_prefix, input_schema, output_schema)
VALUES (
    'cloud_cost.bills_list',
    'CloudCost 月度账单列表',
    $$用途: 月度账单列表 (cloud_finance / cloud_admin).
参数: month YYYY-MM / status / page / page_size.$$,
    'cloud_cost',
    'http_adapter',
    '{"base_url_env": "CLOUDCOST_API_BASE", "method": "GET", "param_map": {"month": "query", "page": "query", "page_size": "query", "status": "query"}, "path": "/api/bills/", "retries": 0, "timeout_sec": 45}'::jsonb,
    'user_passthrough',
    NULL,
    'Authorization',
    'Bearer ',
    '{"additionalProperties": false, "properties": {"month": {"pattern": "^\\d{4}-\\d{2}$", "type": "string"}, "page": {"default": 1, "minimum": 1, "type": "integer"}, "page_size": {"default": 100, "maximum": 500, "minimum": 1, "type": "integer"}, "status": {"enum": ["draft", "confirmed", "paid"], "type": "string"}}, "type": "object"}'::jsonb,
    NULL
)
ON CONFLICT (name) DO UPDATE SET
    display_name = EXCLUDED.display_name,
    description = EXCLUDED.description,
    category = EXCLUDED.category,
    dispatcher = EXCLUDED.dispatcher,
    config = EXCLUDED.config,
    auth_mode = EXCLUDED.auth_mode,
    secret_env_name = EXCLUDED.secret_env_name,
    auth_header = EXCLUDED.auth_header,
    auth_prefix = EXCLUDED.auth_prefix,
    input_schema = EXCLUDED.input_schema,
    output_schema = EXCLUDED.output_schema;

INSERT INTO chat_gw.tools
    (name, display_name, description, category, dispatcher, config,
     auth_mode, secret_env_name, auth_header, auth_prefix, input_schema, output_schema)
VALUES (
    'cloud_cost.bill_get',
    'CloudCost 月度账单详情',
    $$用途: 单张月度账单详情 (cloud_finance / cloud_admin).
路径: bill_id 必填.$$,
    'cloud_cost',
    'http_adapter',
    '{"base_url_env": "CLOUDCOST_API_BASE", "method": "GET", "param_map": {"bill_id": "path"}, "path": "/api/bills/{bill_id}", "retries": 0, "timeout_sec": 45}'::jsonb,
    'user_passthrough',
    NULL,
    'Authorization',
    'Bearer ',
    '{"additionalProperties": false, "properties": {"bill_id": {"minimum": 1, "type": "integer"}}, "required": ["bill_id"], "type": "object"}'::jsonb,
    NULL
)
ON CONFLICT (name) DO UPDATE SET
    display_name = EXCLUDED.display_name,
    description = EXCLUDED.description,
    category = EXCLUDED.category,
    dispatcher = EXCLUDED.dispatcher,
    config = EXCLUDED.config,
    auth_mode = EXCLUDED.auth_mode,
    secret_env_name = EXCLUDED.secret_env_name,
    auth_header = EXCLUDED.auth_header,
    auth_prefix = EXCLUDED.auth_prefix,
    input_schema = EXCLUDED.input_schema,
    output_schema = EXCLUDED.output_schema;

INSERT INTO chat_gw.tools
    (name, display_name, description, category, dispatcher, config,
     auth_mode, secret_env_name, auth_header, auth_prefix, input_schema, output_schema)
VALUES (
    'cloud_cost.alerts_rule_status',
    'CloudCost 告警规则执行态',
    $$用途: 查看告警规则 vs 实际用量 (触发态 / 阈值 / 当前值). 任意登录角色可读.
参数: month YYYY-MM 可选, 默认当月.$$,
    'cloud_cost',
    'http_adapter',
    '{"base_url_env": "CLOUDCOST_API_BASE", "method": "GET", "param_map": {"month": "query"}, "path": "/api/alerts/rule-status", "retries": 0, "timeout_sec": 45}'::jsonb,
    'user_passthrough',
    NULL,
    'Authorization',
    'Bearer ',
    '{"additionalProperties": false, "properties": {"month": {"pattern": "^\\d{4}-\\d{2}$", "type": "string"}}, "type": "object"}'::jsonb,
    NULL
)
ON CONFLICT (name) DO UPDATE SET
    display_name = EXCLUDED.display_name,
    description = EXCLUDED.description,
    category = EXCLUDED.category,
    dispatcher = EXCLUDED.dispatcher,
    config = EXCLUDED.config,
    auth_mode = EXCLUDED.auth_mode,
    secret_env_name = EXCLUDED.secret_env_name,
    auth_header = EXCLUDED.auth_header,
    auth_prefix = EXCLUDED.auth_prefix,
    input_schema = EXCLUDED.input_schema,
    output_schema = EXCLUDED.output_schema;

INSERT INTO chat_gw.tools
    (name, display_name, description, category, dispatcher, config,
     auth_mode, secret_env_name, auth_header, auth_prefix, input_schema, output_schema)
VALUES (
    'cloud_cost.alerts_rules_list',
    'CloudCost 告警规则列表',
    $$用途: 告警规则配置只读列表. 任意登录角色可读.$$,
    'cloud_cost',
    'http_adapter',
    '{"base_url_env": "CLOUDCOST_API_BASE", "method": "GET", "path": "/api/alerts/rules/", "retries": 0, "timeout_sec": 45}'::jsonb,
    'user_passthrough',
    NULL,
    'Authorization',
    'Bearer ',
    '{"additionalProperties": false, "properties": {}, "type": "object"}'::jsonb,
    NULL
)
ON CONFLICT (name) DO UPDATE SET
    display_name = EXCLUDED.display_name,
    description = EXCLUDED.description,
    category = EXCLUDED.category,
    dispatcher = EXCLUDED.dispatcher,
    config = EXCLUDED.config,
    auth_mode = EXCLUDED.auth_mode,
    secret_env_name = EXCLUDED.secret_env_name,
    auth_header = EXCLUDED.auth_header,
    auth_prefix = EXCLUDED.auth_prefix,
    input_schema = EXCLUDED.input_schema,
    output_schema = EXCLUDED.output_schema;

INSERT INTO chat_gw.tools
    (name, display_name, description, category, dispatcher, config,
     auth_mode, secret_env_name, auth_header, auth_prefix, input_schema, output_schema)
VALUES (
    'cloud_cost.alerts_history',
    'CloudCost 告警历史',
    $$用途: 告警历史记录.
参数: rule_id 可选; limit 1-200 默认 50.$$,
    'cloud_cost',
    'http_adapter',
    '{"base_url_env": "CLOUDCOST_API_BASE", "method": "GET", "param_map": {"limit": "query", "rule_id": "query"}, "path": "/api/alerts/history", "retries": 0, "timeout_sec": 45}'::jsonb,
    'user_passthrough',
    NULL,
    'Authorization',
    'Bearer ',
    '{"additionalProperties": false, "properties": {"limit": {"default": 50, "maximum": 200, "minimum": 1, "type": "integer"}, "rule_id": {"minimum": 1, "type": "integer"}}, "type": "object"}'::jsonb,
    NULL
)
ON CONFLICT (name) DO UPDATE SET
    display_name = EXCLUDED.display_name,
    description = EXCLUDED.description,
    category = EXCLUDED.category,
    dispatcher = EXCLUDED.dispatcher,
    config = EXCLUDED.config,
    auth_mode = EXCLUDED.auth_mode,
    secret_env_name = EXCLUDED.secret_env_name,
    auth_header = EXCLUDED.auth_header,
    auth_prefix = EXCLUDED.auth_prefix,
    input_schema = EXCLUDED.input_schema,
    output_schema = EXCLUDED.output_schema;

INSERT INTO chat_gw.tools
    (name, display_name, description, category, dispatcher, config,
     auth_mode, secret_env_name, auth_header, auth_prefix, input_schema, output_schema)
VALUES (
    'cloud_cost.alerts_notifications',
    'CloudCost 告警通知',
    $$用途: 告警通知列表 (只读).
参数: unread_only 布尔; limit 1-100 默认 30.$$,
    'cloud_cost',
    'http_adapter',
    '{"base_url_env": "CLOUDCOST_API_BASE", "method": "GET", "param_map": {"limit": "query", "unread_only": "query"}, "path": "/api/alerts/notifications", "retries": 0, "timeout_sec": 45}'::jsonb,
    'user_passthrough',
    NULL,
    'Authorization',
    'Bearer ',
    '{"additionalProperties": false, "properties": {"limit": {"default": 30, "maximum": 100, "minimum": 1, "type": "integer"}, "unread_only": {"type": "boolean"}}, "type": "object"}'::jsonb,
    NULL
)
ON CONFLICT (name) DO UPDATE SET
    display_name = EXCLUDED.display_name,
    description = EXCLUDED.description,
    category = EXCLUDED.category,
    dispatcher = EXCLUDED.dispatcher,
    config = EXCLUDED.config,
    auth_mode = EXCLUDED.auth_mode,
    secret_env_name = EXCLUDED.secret_env_name,
    auth_header = EXCLUDED.auth_header,
    auth_prefix = EXCLUDED.auth_prefix,
    input_schema = EXCLUDED.input_schema,
    output_schema = EXCLUDED.output_schema;

INSERT INTO chat_gw.tools
    (name, display_name, description, category, dispatcher, config,
     auth_mode, secret_env_name, auth_header, auth_prefix, input_schema, output_schema)
VALUES (
    'cloud_cost.resources_list',
    'CloudCost 资源清单',
    $$用途: 资源清单分页 (按可见数据源过滤).
参数: provider / project_id / resource_type / page / page_size.$$,
    'cloud_cost',
    'http_adapter',
    '{"base_url_env": "CLOUDCOST_API_BASE", "method": "GET", "param_map": {"page": "query", "page_size": "query", "project_id": "query", "provider": "query", "resource_type": "query"}, "path": "/api/resources/", "retries": 0, "timeout_sec": 45}'::jsonb,
    'user_passthrough',
    NULL,
    'Authorization',
    'Bearer ',
    '{"additionalProperties": false, "properties": {"page": {"default": 1, "minimum": 1, "type": "integer"}, "page_size": {"default": 50, "maximum": 500, "minimum": 1, "type": "integer"}, "project_id": {"type": "string"}, "provider": {"enum": ["aws", "gcp", "azure", "taiji"], "type": "string"}, "resource_type": {"type": "string"}}, "type": "object"}'::jsonb,
    NULL
)
ON CONFLICT (name) DO UPDATE SET
    display_name = EXCLUDED.display_name,
    description = EXCLUDED.description,
    category = EXCLUDED.category,
    dispatcher = EXCLUDED.dispatcher,
    config = EXCLUDED.config,
    auth_mode = EXCLUDED.auth_mode,
    secret_env_name = EXCLUDED.secret_env_name,
    auth_header = EXCLUDED.auth_header,
    auth_prefix = EXCLUDED.auth_prefix,
    input_schema = EXCLUDED.input_schema,
    output_schema = EXCLUDED.output_schema;

INSERT INTO chat_gw.tools
    (name, display_name, description, category, dispatcher, config,
     auth_mode, secret_env_name, auth_header, auth_prefix, input_schema, output_schema)
VALUES (
    'cloud_cost.resource_get',
    'CloudCost 资源详情',
    $$用途: 单个资源详情.
路径: resource_id 必填.$$,
    'cloud_cost',
    'http_adapter',
    '{"base_url_env": "CLOUDCOST_API_BASE", "method": "GET", "param_map": {"resource_id": "path"}, "path": "/api/resources/{resource_id}", "retries": 0, "timeout_sec": 45}'::jsonb,
    'user_passthrough',
    NULL,
    'Authorization',
    'Bearer ',
    '{"additionalProperties": false, "properties": {"resource_id": {"minimum": 1, "type": "integer"}}, "required": ["resource_id"], "type": "object"}'::jsonb,
    NULL
)
ON CONFLICT (name) DO UPDATE SET
    display_name = EXCLUDED.display_name,
    description = EXCLUDED.description,
    category = EXCLUDED.category,
    dispatcher = EXCLUDED.dispatcher,
    config = EXCLUDED.config,
    auth_mode = EXCLUDED.auth_mode,
    secret_env_name = EXCLUDED.secret_env_name,
    auth_header = EXCLUDED.auth_header,
    auth_prefix = EXCLUDED.auth_prefix,
    input_schema = EXCLUDED.input_schema,
    output_schema = EXCLUDED.output_schema;

INSERT INTO chat_gw.tools
    (name, display_name, description, category, dispatcher, config,
     auth_mode, secret_env_name, auth_header, auth_prefix, input_schema, output_schema)
VALUES (
    'cloud_cost.suppliers_list',
    'CloudCost 供应商列表 (admin)',
    $$用途: 供应商列表 (suppliers 模块为 cloud_admin only).$$,
    'cloud_cost',
    'http_adapter',
    '{"base_url_env": "CLOUDCOST_API_BASE", "method": "GET", "path": "/api/suppliers/", "retries": 0, "timeout_sec": 45}'::jsonb,
    'user_passthrough',
    NULL,
    'Authorization',
    'Bearer ',
    '{"additionalProperties": false, "properties": {}, "type": "object"}'::jsonb,
    NULL
)
ON CONFLICT (name) DO UPDATE SET
    display_name = EXCLUDED.display_name,
    description = EXCLUDED.description,
    category = EXCLUDED.category,
    dispatcher = EXCLUDED.dispatcher,
    config = EXCLUDED.config,
    auth_mode = EXCLUDED.auth_mode,
    secret_env_name = EXCLUDED.secret_env_name,
    auth_header = EXCLUDED.auth_header,
    auth_prefix = EXCLUDED.auth_prefix,
    input_schema = EXCLUDED.input_schema,
    output_schema = EXCLUDED.output_schema;

INSERT INTO chat_gw.tools
    (name, display_name, description, category, dispatcher, config,
     auth_mode, secret_env_name, auth_header, auth_prefix, input_schema, output_schema)
VALUES (
    'cloud_cost.suppliers_supply_sources_all',
    'CloudCost 货源全量 (admin)',
    $$用途: 全部货源下拉, 可按 supplier_id 过滤.
参数: supplier_id 可选.$$,
    'cloud_cost',
    'http_adapter',
    '{"base_url_env": "CLOUDCOST_API_BASE", "method": "GET", "param_map": {"supplier_id": "query"}, "path": "/api/suppliers/supply-sources/all", "retries": 0, "timeout_sec": 45}'::jsonb,
    'user_passthrough',
    NULL,
    'Authorization',
    'Bearer ',
    '{"additionalProperties": false, "properties": {"supplier_id": {"minimum": 1, "type": "integer"}}, "type": "object"}'::jsonb,
    NULL
)
ON CONFLICT (name) DO UPDATE SET
    display_name = EXCLUDED.display_name,
    description = EXCLUDED.description,
    category = EXCLUDED.category,
    dispatcher = EXCLUDED.dispatcher,
    config = EXCLUDED.config,
    auth_mode = EXCLUDED.auth_mode,
    secret_env_name = EXCLUDED.secret_env_name,
    auth_header = EXCLUDED.auth_header,
    auth_prefix = EXCLUDED.auth_prefix,
    input_schema = EXCLUDED.input_schema,
    output_schema = EXCLUDED.output_schema;

INSERT INTO chat_gw.tools
    (name, display_name, description, category, dispatcher, config,
     auth_mode, secret_env_name, auth_header, auth_prefix, input_schema, output_schema)
VALUES (
    'cloud_cost.supplier_supply_sources',
    'CloudCost 供应商下货源 (admin)',
    $$用途: 指定供应商下的货源列表.
路径: supplier_id 必填.$$,
    'cloud_cost',
    'http_adapter',
    '{"base_url_env": "CLOUDCOST_API_BASE", "method": "GET", "param_map": {"supplier_id": "path"}, "path": "/api/suppliers/{supplier_id}/supply-sources", "retries": 0, "timeout_sec": 45}'::jsonb,
    'user_passthrough',
    NULL,
    'Authorization',
    'Bearer ',
    '{"additionalProperties": false, "properties": {"supplier_id": {"minimum": 1, "type": "integer"}}, "required": ["supplier_id"], "type": "object"}'::jsonb,
    NULL
)
ON CONFLICT (name) DO UPDATE SET
    display_name = EXCLUDED.display_name,
    description = EXCLUDED.description,
    category = EXCLUDED.category,
    dispatcher = EXCLUDED.dispatcher,
    config = EXCLUDED.config,
    auth_mode = EXCLUDED.auth_mode,
    secret_env_name = EXCLUDED.secret_env_name,
    auth_header = EXCLUDED.auth_header,
    auth_prefix = EXCLUDED.auth_prefix,
    input_schema = EXCLUDED.input_schema,
    output_schema = EXCLUDED.output_schema;

INSERT INTO chat_gw.tools
    (name, display_name, description, category, dispatcher, config,
     auth_mode, secret_env_name, auth_header, auth_prefix, input_schema, output_schema)
VALUES (
    'cloud_cost.categories_list',
    'CloudCost 费用分类字典 (admin)',
    $$用途: 费用分类字典 (categories 模块 admin only).
markup_rate 为 string (4 位小数).$$,
    'cloud_cost',
    'http_adapter',
    '{"base_url_env": "CLOUDCOST_API_BASE", "method": "GET", "path": "/api/categories/", "retries": 0, "timeout_sec": 45}'::jsonb,
    'user_passthrough',
    NULL,
    'Authorization',
    'Bearer ',
    '{"additionalProperties": false, "properties": {}, "type": "object"}'::jsonb,
    NULL
)
ON CONFLICT (name) DO UPDATE SET
    display_name = EXCLUDED.display_name,
    description = EXCLUDED.description,
    category = EXCLUDED.category,
    dispatcher = EXCLUDED.dispatcher,
    config = EXCLUDED.config,
    auth_mode = EXCLUDED.auth_mode,
    secret_env_name = EXCLUDED.secret_env_name,
    auth_header = EXCLUDED.auth_header,
    auth_prefix = EXCLUDED.auth_prefix,
    input_schema = EXCLUDED.input_schema,
    output_schema = EXCLUDED.output_schema;

INSERT INTO chat_gw.tools
    (name, display_name, description, category, dispatcher, config,
     auth_mode, secret_env_name, auth_header, auth_prefix, input_schema, output_schema)
VALUES (
    'cloud_cost.category_get',
    'CloudCost 费用分类详情 (admin)',
    $$用途: 单个分类 (admin).
路径: category_id 必填.$$,
    'cloud_cost',
    'http_adapter',
    '{"base_url_env": "CLOUDCOST_API_BASE", "method": "GET", "param_map": {"category_id": "path"}, "path": "/api/categories/{category_id}", "retries": 0, "timeout_sec": 45}'::jsonb,
    'user_passthrough',
    NULL,
    'Authorization',
    'Bearer ',
    '{"additionalProperties": false, "properties": {"category_id": {"minimum": 1, "type": "integer"}}, "required": ["category_id"], "type": "object"}'::jsonb,
    NULL
)
ON CONFLICT (name) DO UPDATE SET
    display_name = EXCLUDED.display_name,
    description = EXCLUDED.description,
    category = EXCLUDED.category,
    dispatcher = EXCLUDED.dispatcher,
    config = EXCLUDED.config,
    auth_mode = EXCLUDED.auth_mode,
    secret_env_name = EXCLUDED.secret_env_name,
    auth_header = EXCLUDED.auth_header,
    auth_prefix = EXCLUDED.auth_prefix,
    input_schema = EXCLUDED.input_schema,
    output_schema = EXCLUDED.output_schema;

INSERT INTO chat_gw.tools
    (name, display_name, description, category, dispatcher, config,
     auth_mode, secret_env_name, auth_header, auth_prefix, input_schema, output_schema)
VALUES (
    'cloud_cost.exchange_rates_list',
    'CloudCost 汇率',
    $$用途: 汇率字典 (任意登录可读).
参数: date YYYY-MM-DD 可选; from_currency 可选.$$,
    'cloud_cost',
    'http_adapter',
    '{"base_url_env": "CLOUDCOST_API_BASE", "method": "GET", "param_map": {"date": "query", "from_currency": "query"}, "path": "/api/exchange-rates/", "retries": 0, "timeout_sec": 45}'::jsonb,
    'user_passthrough',
    NULL,
    'Authorization',
    'Bearer ',
    '{"additionalProperties": false, "properties": {"date": {"format": "date", "type": "string"}, "from_currency": {"type": "string"}}, "type": "object"}'::jsonb,
    NULL
)
ON CONFLICT (name) DO UPDATE SET
    display_name = EXCLUDED.display_name,
    description = EXCLUDED.description,
    category = EXCLUDED.category,
    dispatcher = EXCLUDED.dispatcher,
    config = EXCLUDED.config,
    auth_mode = EXCLUDED.auth_mode,
    secret_env_name = EXCLUDED.secret_env_name,
    auth_header = EXCLUDED.auth_header,
    auth_prefix = EXCLUDED.auth_prefix,
    input_schema = EXCLUDED.input_schema,
    output_schema = EXCLUDED.output_schema;

INSERT INTO chat_gw.tools
    (name, display_name, description, category, dispatcher, config,
     auth_mode, secret_env_name, auth_header, auth_prefix, input_schema, output_schema)
VALUES (
    'cloud_cost.data_sources_list',
    'CloudCost 数据源列表 (admin)',
    $$用途: 数据源列表 (data_sources 模块 admin only).$$,
    'cloud_cost',
    'http_adapter',
    '{"base_url_env": "CLOUDCOST_API_BASE", "method": "GET", "path": "/api/data-sources/", "retries": 0, "timeout_sec": 45}'::jsonb,
    'user_passthrough',
    NULL,
    'Authorization',
    'Bearer ',
    '{"additionalProperties": false, "properties": {}, "type": "object"}'::jsonb,
    NULL
)
ON CONFLICT (name) DO UPDATE SET
    display_name = EXCLUDED.display_name,
    description = EXCLUDED.description,
    category = EXCLUDED.category,
    dispatcher = EXCLUDED.dispatcher,
    config = EXCLUDED.config,
    auth_mode = EXCLUDED.auth_mode,
    secret_env_name = EXCLUDED.secret_env_name,
    auth_header = EXCLUDED.auth_header,
    auth_prefix = EXCLUDED.auth_prefix,
    input_schema = EXCLUDED.input_schema,
    output_schema = EXCLUDED.output_schema;

INSERT INTO chat_gw.tools
    (name, display_name, description, category, dispatcher, config,
     auth_mode, secret_env_name, auth_header, auth_prefix, input_schema, output_schema)
VALUES (
    'cloud_cost.data_source_get',
    'CloudCost 数据源详情 (admin)',
    $$用途: 单个数据源配置与最近同步状态.
路径: ds_id 必填.$$,
    'cloud_cost',
    'http_adapter',
    '{"base_url_env": "CLOUDCOST_API_BASE", "method": "GET", "param_map": {"ds_id": "path"}, "path": "/api/data-sources/{ds_id}", "retries": 0, "timeout_sec": 45}'::jsonb,
    'user_passthrough',
    NULL,
    'Authorization',
    'Bearer ',
    '{"additionalProperties": false, "properties": {"ds_id": {"minimum": 1, "type": "integer"}}, "required": ["ds_id"], "type": "object"}'::jsonb,
    NULL
)
ON CONFLICT (name) DO UPDATE SET
    display_name = EXCLUDED.display_name,
    description = EXCLUDED.description,
    category = EXCLUDED.category,
    dispatcher = EXCLUDED.dispatcher,
    config = EXCLUDED.config,
    auth_mode = EXCLUDED.auth_mode,
    secret_env_name = EXCLUDED.secret_env_name,
    auth_header = EXCLUDED.auth_header,
    auth_prefix = EXCLUDED.auth_prefix,
    input_schema = EXCLUDED.input_schema,
    output_schema = EXCLUDED.output_schema;

DELETE FROM chat_gw.tool_role_grants
WHERE tool_id IN (SELECT id FROM chat_gw.tools WHERE name IN ('cloud_cost.health', 'cloud_cost.auth_me', 'cloud_cost.sync_last', 'cloud_cost.dashboard_bundle', 'cloud_cost.dashboard_overview', 'cloud_cost.dashboard_trend', 'cloud_cost.dashboard_by_provider', 'cloud_cost.dashboard_by_category', 'cloud_cost.dashboard_by_project', 'cloud_cost.dashboard_by_service', 'cloud_cost.dashboard_by_region', 'cloud_cost.dashboard_top_growth', 'cloud_cost.dashboard_unassigned', 'cloud_cost.metering_summary', 'cloud_cost.metering_daily', 'cloud_cost.metering_by_service', 'cloud_cost.metering_detail', 'cloud_cost.metering_detail_count', 'cloud_cost.metering_products', 'cloud_cost.billing_detail', 'cloud_cost.billing_detail_count', 'cloud_cost.service_accounts_list', 'cloud_cost.service_account_get', 'cloud_cost.service_account_costs', 'cloud_cost.service_accounts_daily_report', 'cloud_cost.projects_list', 'cloud_cost.project_get', 'cloud_cost.project_assignment_logs', 'cloud_cost.bills_list', 'cloud_cost.bill_get', 'cloud_cost.alerts_rule_status', 'cloud_cost.alerts_rules_list', 'cloud_cost.alerts_history', 'cloud_cost.alerts_notifications', 'cloud_cost.resources_list', 'cloud_cost.resource_get', 'cloud_cost.suppliers_list', 'cloud_cost.suppliers_supply_sources_all', 'cloud_cost.supplier_supply_sources', 'cloud_cost.categories_list', 'cloud_cost.category_get', 'cloud_cost.exchange_rates_list', 'cloud_cost.data_sources_list', 'cloud_cost.data_source_get'));

INSERT INTO chat_gw.tool_role_grants (tool_id, role)
SELECT id, r FROM chat_gw.tools, unnest(ARRAY['cloud_admin', 'cloud_ops', 'cloud_finance', 'cloud_viewer']) AS r
WHERE chat_gw.tools.name = 'cloud_cost.health'
ON CONFLICT DO NOTHING;

INSERT INTO chat_gw.tool_role_grants (tool_id, role)
SELECT id, r FROM chat_gw.tools, unnest(ARRAY['cloud_admin', 'cloud_ops', 'cloud_finance', 'cloud_viewer']) AS r
WHERE chat_gw.tools.name = 'cloud_cost.auth_me'
ON CONFLICT DO NOTHING;

INSERT INTO chat_gw.tool_role_grants (tool_id, role)
SELECT id, r FROM chat_gw.tools, unnest(ARRAY['cloud_admin', 'cloud_ops']) AS r
WHERE chat_gw.tools.name = 'cloud_cost.sync_last'
ON CONFLICT DO NOTHING;

INSERT INTO chat_gw.tool_role_grants (tool_id, role)
SELECT id, r FROM chat_gw.tools, unnest(ARRAY['cloud_admin', 'cloud_ops', 'cloud_finance', 'cloud_viewer']) AS r
WHERE chat_gw.tools.name = 'cloud_cost.dashboard_bundle'
ON CONFLICT DO NOTHING;

INSERT INTO chat_gw.tool_role_grants (tool_id, role)
SELECT id, r FROM chat_gw.tools, unnest(ARRAY['cloud_admin', 'cloud_ops', 'cloud_finance', 'cloud_viewer']) AS r
WHERE chat_gw.tools.name = 'cloud_cost.dashboard_overview'
ON CONFLICT DO NOTHING;

INSERT INTO chat_gw.tool_role_grants (tool_id, role)
SELECT id, r FROM chat_gw.tools, unnest(ARRAY['cloud_admin', 'cloud_ops', 'cloud_finance', 'cloud_viewer']) AS r
WHERE chat_gw.tools.name = 'cloud_cost.dashboard_trend'
ON CONFLICT DO NOTHING;

INSERT INTO chat_gw.tool_role_grants (tool_id, role)
SELECT id, r FROM chat_gw.tools, unnest(ARRAY['cloud_admin', 'cloud_ops', 'cloud_finance', 'cloud_viewer']) AS r
WHERE chat_gw.tools.name = 'cloud_cost.dashboard_by_provider'
ON CONFLICT DO NOTHING;

INSERT INTO chat_gw.tool_role_grants (tool_id, role)
SELECT id, r FROM chat_gw.tools, unnest(ARRAY['cloud_admin', 'cloud_ops', 'cloud_finance', 'cloud_viewer']) AS r
WHERE chat_gw.tools.name = 'cloud_cost.dashboard_by_category'
ON CONFLICT DO NOTHING;

INSERT INTO chat_gw.tool_role_grants (tool_id, role)
SELECT id, r FROM chat_gw.tools, unnest(ARRAY['cloud_admin', 'cloud_ops', 'cloud_finance', 'cloud_viewer']) AS r
WHERE chat_gw.tools.name = 'cloud_cost.dashboard_by_project'
ON CONFLICT DO NOTHING;

INSERT INTO chat_gw.tool_role_grants (tool_id, role)
SELECT id, r FROM chat_gw.tools, unnest(ARRAY['cloud_admin', 'cloud_ops', 'cloud_finance', 'cloud_viewer']) AS r
WHERE chat_gw.tools.name = 'cloud_cost.dashboard_by_service'
ON CONFLICT DO NOTHING;

INSERT INTO chat_gw.tool_role_grants (tool_id, role)
SELECT id, r FROM chat_gw.tools, unnest(ARRAY['cloud_admin', 'cloud_ops', 'cloud_finance', 'cloud_viewer']) AS r
WHERE chat_gw.tools.name = 'cloud_cost.dashboard_by_region'
ON CONFLICT DO NOTHING;

INSERT INTO chat_gw.tool_role_grants (tool_id, role)
SELECT id, r FROM chat_gw.tools, unnest(ARRAY['cloud_admin', 'cloud_ops', 'cloud_finance', 'cloud_viewer']) AS r
WHERE chat_gw.tools.name = 'cloud_cost.dashboard_top_growth'
ON CONFLICT DO NOTHING;

INSERT INTO chat_gw.tool_role_grants (tool_id, role)
SELECT id, r FROM chat_gw.tools, unnest(ARRAY['cloud_admin', 'cloud_ops', 'cloud_finance', 'cloud_viewer']) AS r
WHERE chat_gw.tools.name = 'cloud_cost.dashboard_unassigned'
ON CONFLICT DO NOTHING;

INSERT INTO chat_gw.tool_role_grants (tool_id, role)
SELECT id, r FROM chat_gw.tools, unnest(ARRAY['cloud_admin', 'cloud_ops', 'cloud_finance', 'cloud_viewer']) AS r
WHERE chat_gw.tools.name = 'cloud_cost.metering_summary'
ON CONFLICT DO NOTHING;

INSERT INTO chat_gw.tool_role_grants (tool_id, role)
SELECT id, r FROM chat_gw.tools, unnest(ARRAY['cloud_admin', 'cloud_ops', 'cloud_finance', 'cloud_viewer']) AS r
WHERE chat_gw.tools.name = 'cloud_cost.metering_daily'
ON CONFLICT DO NOTHING;

INSERT INTO chat_gw.tool_role_grants (tool_id, role)
SELECT id, r FROM chat_gw.tools, unnest(ARRAY['cloud_admin', 'cloud_ops', 'cloud_finance', 'cloud_viewer']) AS r
WHERE chat_gw.tools.name = 'cloud_cost.metering_by_service'
ON CONFLICT DO NOTHING;

INSERT INTO chat_gw.tool_role_grants (tool_id, role)
SELECT id, r FROM chat_gw.tools, unnest(ARRAY['cloud_admin', 'cloud_ops', 'cloud_finance', 'cloud_viewer']) AS r
WHERE chat_gw.tools.name = 'cloud_cost.metering_detail'
ON CONFLICT DO NOTHING;

INSERT INTO chat_gw.tool_role_grants (tool_id, role)
SELECT id, r FROM chat_gw.tools, unnest(ARRAY['cloud_admin', 'cloud_ops', 'cloud_finance', 'cloud_viewer']) AS r
WHERE chat_gw.tools.name = 'cloud_cost.metering_detail_count'
ON CONFLICT DO NOTHING;

INSERT INTO chat_gw.tool_role_grants (tool_id, role)
SELECT id, r FROM chat_gw.tools, unnest(ARRAY['cloud_admin', 'cloud_ops', 'cloud_finance', 'cloud_viewer']) AS r
WHERE chat_gw.tools.name = 'cloud_cost.metering_products'
ON CONFLICT DO NOTHING;

INSERT INTO chat_gw.tool_role_grants (tool_id, role)
SELECT id, r FROM chat_gw.tools, unnest(ARRAY['cloud_admin', 'cloud_ops', 'cloud_finance', 'cloud_viewer']) AS r
WHERE chat_gw.tools.name = 'cloud_cost.billing_detail'
ON CONFLICT DO NOTHING;

INSERT INTO chat_gw.tool_role_grants (tool_id, role)
SELECT id, r FROM chat_gw.tools, unnest(ARRAY['cloud_admin', 'cloud_ops', 'cloud_finance', 'cloud_viewer']) AS r
WHERE chat_gw.tools.name = 'cloud_cost.billing_detail_count'
ON CONFLICT DO NOTHING;

INSERT INTO chat_gw.tool_role_grants (tool_id, role)
SELECT id, r FROM chat_gw.tools, unnest(ARRAY['cloud_admin', 'cloud_ops', 'cloud_finance', 'cloud_viewer']) AS r
WHERE chat_gw.tools.name = 'cloud_cost.service_accounts_list'
ON CONFLICT DO NOTHING;

INSERT INTO chat_gw.tool_role_grants (tool_id, role)
SELECT id, r FROM chat_gw.tools, unnest(ARRAY['cloud_admin', 'cloud_ops', 'cloud_finance', 'cloud_viewer']) AS r
WHERE chat_gw.tools.name = 'cloud_cost.service_account_get'
ON CONFLICT DO NOTHING;

INSERT INTO chat_gw.tool_role_grants (tool_id, role)
SELECT id, r FROM chat_gw.tools, unnest(ARRAY['cloud_admin', 'cloud_ops', 'cloud_finance', 'cloud_viewer']) AS r
WHERE chat_gw.tools.name = 'cloud_cost.service_account_costs'
ON CONFLICT DO NOTHING;

INSERT INTO chat_gw.tool_role_grants (tool_id, role)
SELECT id, r FROM chat_gw.tools, unnest(ARRAY['cloud_admin', 'cloud_ops', 'cloud_finance', 'cloud_viewer']) AS r
WHERE chat_gw.tools.name = 'cloud_cost.service_accounts_daily_report'
ON CONFLICT DO NOTHING;

INSERT INTO chat_gw.tool_role_grants (tool_id, role)
SELECT id, r FROM chat_gw.tools, unnest(ARRAY['cloud_admin', 'cloud_ops', 'cloud_finance', 'cloud_viewer']) AS r
WHERE chat_gw.tools.name = 'cloud_cost.projects_list'
ON CONFLICT DO NOTHING;

INSERT INTO chat_gw.tool_role_grants (tool_id, role)
SELECT id, r FROM chat_gw.tools, unnest(ARRAY['cloud_admin', 'cloud_ops', 'cloud_finance', 'cloud_viewer']) AS r
WHERE chat_gw.tools.name = 'cloud_cost.project_get'
ON CONFLICT DO NOTHING;

INSERT INTO chat_gw.tool_role_grants (tool_id, role)
SELECT id, r FROM chat_gw.tools, unnest(ARRAY['cloud_admin', 'cloud_ops', 'cloud_finance', 'cloud_viewer']) AS r
WHERE chat_gw.tools.name = 'cloud_cost.project_assignment_logs'
ON CONFLICT DO NOTHING;

INSERT INTO chat_gw.tool_role_grants (tool_id, role)
SELECT id, r FROM chat_gw.tools, unnest(ARRAY['cloud_admin', 'cloud_finance']) AS r
WHERE chat_gw.tools.name = 'cloud_cost.bills_list'
ON CONFLICT DO NOTHING;

INSERT INTO chat_gw.tool_role_grants (tool_id, role)
SELECT id, r FROM chat_gw.tools, unnest(ARRAY['cloud_admin', 'cloud_finance']) AS r
WHERE chat_gw.tools.name = 'cloud_cost.bill_get'
ON CONFLICT DO NOTHING;

INSERT INTO chat_gw.tool_role_grants (tool_id, role)
SELECT id, r FROM chat_gw.tools, unnest(ARRAY['cloud_admin', 'cloud_ops', 'cloud_finance', 'cloud_viewer']) AS r
WHERE chat_gw.tools.name = 'cloud_cost.alerts_rule_status'
ON CONFLICT DO NOTHING;

INSERT INTO chat_gw.tool_role_grants (tool_id, role)
SELECT id, r FROM chat_gw.tools, unnest(ARRAY['cloud_admin', 'cloud_ops', 'cloud_finance', 'cloud_viewer']) AS r
WHERE chat_gw.tools.name = 'cloud_cost.alerts_rules_list'
ON CONFLICT DO NOTHING;

INSERT INTO chat_gw.tool_role_grants (tool_id, role)
SELECT id, r FROM chat_gw.tools, unnest(ARRAY['cloud_admin', 'cloud_ops', 'cloud_finance', 'cloud_viewer']) AS r
WHERE chat_gw.tools.name = 'cloud_cost.alerts_history'
ON CONFLICT DO NOTHING;

INSERT INTO chat_gw.tool_role_grants (tool_id, role)
SELECT id, r FROM chat_gw.tools, unnest(ARRAY['cloud_admin', 'cloud_ops', 'cloud_finance', 'cloud_viewer']) AS r
WHERE chat_gw.tools.name = 'cloud_cost.alerts_notifications'
ON CONFLICT DO NOTHING;

INSERT INTO chat_gw.tool_role_grants (tool_id, role)
SELECT id, r FROM chat_gw.tools, unnest(ARRAY['cloud_admin', 'cloud_ops', 'cloud_finance', 'cloud_viewer']) AS r
WHERE chat_gw.tools.name = 'cloud_cost.resources_list'
ON CONFLICT DO NOTHING;

INSERT INTO chat_gw.tool_role_grants (tool_id, role)
SELECT id, r FROM chat_gw.tools, unnest(ARRAY['cloud_admin', 'cloud_ops', 'cloud_finance', 'cloud_viewer']) AS r
WHERE chat_gw.tools.name = 'cloud_cost.resource_get'
ON CONFLICT DO NOTHING;

INSERT INTO chat_gw.tool_role_grants (tool_id, role)
SELECT id, r FROM chat_gw.tools, unnest(ARRAY['cloud_admin']) AS r
WHERE chat_gw.tools.name = 'cloud_cost.suppliers_list'
ON CONFLICT DO NOTHING;

INSERT INTO chat_gw.tool_role_grants (tool_id, role)
SELECT id, r FROM chat_gw.tools, unnest(ARRAY['cloud_admin']) AS r
WHERE chat_gw.tools.name = 'cloud_cost.suppliers_supply_sources_all'
ON CONFLICT DO NOTHING;

INSERT INTO chat_gw.tool_role_grants (tool_id, role)
SELECT id, r FROM chat_gw.tools, unnest(ARRAY['cloud_admin']) AS r
WHERE chat_gw.tools.name = 'cloud_cost.supplier_supply_sources'
ON CONFLICT DO NOTHING;

INSERT INTO chat_gw.tool_role_grants (tool_id, role)
SELECT id, r FROM chat_gw.tools, unnest(ARRAY['cloud_admin']) AS r
WHERE chat_gw.tools.name = 'cloud_cost.categories_list'
ON CONFLICT DO NOTHING;

INSERT INTO chat_gw.tool_role_grants (tool_id, role)
SELECT id, r FROM chat_gw.tools, unnest(ARRAY['cloud_admin']) AS r
WHERE chat_gw.tools.name = 'cloud_cost.category_get'
ON CONFLICT DO NOTHING;

INSERT INTO chat_gw.tool_role_grants (tool_id, role)
SELECT id, r FROM chat_gw.tools, unnest(ARRAY['cloud_admin', 'cloud_ops', 'cloud_finance', 'cloud_viewer']) AS r
WHERE chat_gw.tools.name = 'cloud_cost.exchange_rates_list'
ON CONFLICT DO NOTHING;

INSERT INTO chat_gw.tool_role_grants (tool_id, role)
SELECT id, r FROM chat_gw.tools, unnest(ARRAY['cloud_admin']) AS r
WHERE chat_gw.tools.name = 'cloud_cost.data_sources_list'
ON CONFLICT DO NOTHING;

INSERT INTO chat_gw.tool_role_grants (tool_id, role)
SELECT id, r FROM chat_gw.tools, unnest(ARRAY['cloud_admin']) AS r
WHERE chat_gw.tools.name = 'cloud_cost.data_source_get'
ON CONFLICT DO NOTHING;

COMMIT;
